- README.md
Fix svg url for license badge. 
Follow up https://github.com/ansible/dispatcher/pull/59
> chore: fix license badge svg

- dispatcher/main.py
- dispatcher/pool.py
- dispatcher/producers/base.py
- dispatcher/producers/brokered.py
- dispatcher/producers/scheduled.py
- dispatcher/publish.py
- dispatcher/registry.py
- tests/integration/test_pool.py
- tests/unit/test_registry.py
- tools/test_methods.py
- tools/write_messages.py
Fixes https://github.com/ansible/dispatcher/issues/54
~Obviously this needs an integration test~, but I wanted to just get implementation structure now. It is functional, tested with the demo script.
EDIT: added tests
```
ERROR:dispatcher.worker.task:Worker 1 task canceled (uuid=1db13c11-a50a-4b0a-91c7-8cbc401c7436)
Traceback (most recent call last):
File "/home/arominge/repos/dispatcher/dispatcher/worker/task.py", line 84, in run_callable
return _call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^
File "/home/arominge/repos/dispatcher/tools/test_methods.py", line 28, in task_has_timeout
time.sleep(5)
File "/home/arominge/repos/dispatcher/dispatcher/worker/task.py", line 31, in task_cancel
raise DispatcherCancel
dispatcher.worker.task.DispatcherCancel
DEBUG:dispatcher.pool:Worker 1 finished task …
```
> Add task timeout

- dispatcher/pool.py
- dispatcher/process.py
- tests/unit/service/test_process.py
This is pre-work before introducing use of "forkserver".
As we introduce that new method of forking, my plan is to preserve the current logic. Instead of replacing, this will be a configurable class.
For now, this enabling change attempts to quarantine all interactions with the python `multiprocessing` library into a new `process` module. This leaves `pool` as a module highly specialized on asyncio task management and balancing of capacity.
> Separate process management out of pool

- pyproject.toml
It was never needed to begin with, as `setuptools` would auto-depend on it when building wheels in the past, anyway. But nowadays, `wheel` moved inside of `setuptools` even (during last year's PyCon US Sprints, and I was helping a bit, actually).
> Drop the unnecessary `wheel` entry from build deps

- dispatcher/producers/scheduled.py
- dispatcher/registry.py
- dispatcher/worker/task.py
- tests/data/nested/methods.py
- tests/data/nested/nested_registry.py
- tests/unit/service/producers/test_scheduled_producer.py
- tests/unit/test_registry.py
- tests/unit/worker/test_task_worker.py
Fixes https://github.com/ansible/dispatcher/issues/82
There's 3 semi-related things going on, so I'll go through in the order in which I approached them.
1. Scheduled tasks didn't properly respect `bind=True`, because all the registry logic was never adopted in the ScheduledProducer, like, at all. But the fix _for this_ assuming that imports are already in place, is to move the application of the "bind" argument, specifically to the worker. Why only this? It just happens to be the only option that affects behavior on the worker, and does not affect behavior in the parent process. It's just... the only one that does that.
2. Remember that qualifier "assuming that imports are already in place". Well this isn't a good assumption. So if they're not, we'll have a "miss", not finding the method …
> Fix integration bugs between scheduled producer, `@task` decorator and registry

- dispatcher/brokers/pg_notify.py
- dispatcher/control.py
- dispatcher/producers/brokered.py
- dispatcher/service/main.py
- dispatcher/service/pool.py
- dispatcher/service/tasks.py
- tests/integration/test_main.py
- tools/write_messages.py
This changes the implementation of the control-and-reply pattern so that reply messages are sent directly from the main asyncio code, instead of sending them back using the workers in synchronous code.
I had previously attempted this and failed, discovering that it would hang when trying to send the reply. After giving it another shot today, I discovered that this behavior is described in https://github.com/psycopg/psycopg/issues/340 upstream. This implements a solution that is compliant with the suggested use of the psycopg library, which is that we exit the `async for` loop before sending the reply, and then continue the `while True:` loop which already exists.
There are some trade-offs involved, in the AWX dispatcher, we used a different connection to send the reply. This is a bad …
> Send reply messages from the main process

- dispatcher.yml
- dispatcher/producers/__init__.py
- dispatcher/producers/on_start.py
- dispatcher/producers/scheduled.py
- docs/config.md
- schema.json
- tests/integration/test_producers.py
Fixes https://github.com/ansible/dispatcher/issues/79
You can see this in the output for the demo:
```
INFO:dispatcher.service.main:Connecting dispatcher signal handling
DEBUG:dispatcher.service.main:Filling the worker pool
DEBUG:dispatcher.service.main:Starting task production
DEBUG:dispatcher.producers.on_start:Produced on-start task: lambda: print("This task runs on startup")
WARNING:dispatcher.service.pool:Queueing task (uuid=on-start-0), ran out of workers, queued_ct=0
INFO:dispatcher.service.main:Dispatcher running forever, or until shutdown command
DEBUG:dispatcher.service.pool:Starting subprocess for worker 0
DEBUG:dispatcher.service.pool:Worker 0 pid=437154 subprocess has spawned
DEBUG:dispatcher.service.pool:Starting subprocess for worker 1
DEBUG:dispatcher.service.pool:Worker 1 …
```
> Producer for running tasks on start

- dispatcher.yml
- dispatcher/factories.py
- dispatcher/service/control_tasks.py
- dispatcher/service/main.py
- dispatcher/service/pool.py
- run_demo.py
- schema.json
- tests/integration/test_main.py
This is a re-do of https://github.com/ansible/dispatcher/pull/76 that takes the good and leaves the bad. I'm still going to mark it:
Fixes https://github.com/ansible/dispatcher/issues/58
Even though the design has changed.
```
$ ./run_demo.py 
writing some basic test messages
writing 15 messages fast
-------- Actions involving control-and-reply ---------
performing a task cancel
[
{
"queued-16": {
"task": "lambda: __import__(\"time\").sleep(3.1415)",
"uuid": "foobar",
"channel": "test_channel"
},
"node_id": "1b0e8049-88f1-48d7-94b5-fc3e1761f4d0"
}
]
finding a running task by its task name
[
{
"queued-16": {
"task": "lambda: __import__(\"time\").sleep(3.1415)",
"uuid": "foobar2",
"channel": "test_channel"
},
"node_id": "1b0e8049-88f1-48d7-94b5-fc3e1761f4d0"
}
]
getting worker status
[
{ …
```
> Add "worker" control command, add `node_id` to identify service

- dispatcher/factories.py
- dispatcher/service/pool.py
- dispatcher/service/process.py
- dispatcher/worker/task.py
- tests/unit/service/test_process.py
Totally random code organization nit this is trying to get out of the way -
When you look at it, it's clear that `WorkerPool` has no right to have `settings` in its kwargs. It does nothing with it other than to pass it on to the `ProcessManager` class. And the factories could just as well pass the settings to that class. So this makes that change.
The hard, ugly, part about this is that the arguments to `work_loop` get reorganized. Right now it's just an ordered list. I would be open to making these kwargs, I think that still works. The approach I'm going with now, is that we just order them in the order in which we build them. So that starts with data from `WorkerPool` and then makes its way in, from left-to-right, outer-to-inner.
> Pass settings in process, not pool, class. Use kwargs for `work_loop`

- tests/unit/service/producers/test_scheduled_producer.py
You can find other definitions of `fatal_error_callback`, and the expectation is that it's synchronous. IIRC, this was more-so error handling of the test, so it's not surprising this slipped by.
> Fix warning about method not awaited

- tests/integration/test_producers.py
Lambda functions don't use `return`. I have forgotten this detail many times.
> Fix test giving error in output

- dispatcher/registry.py
- dispatcher/worker/task.py
- tests/data/methods.py
- tests/integration/test_callable_queues.py
- tests/integration/test_main.py
Discovered bug in:
https://github.com/AlanCoding/awx/tree/feature_dispatcher
```
In [14]: [dmethod for dmethod in registry.registry][0].get_async_body()
Out[14]: 
{'queue': <function awx.main.dispatch.get_task_queuename()>,
'task': 'awx.main.tasks.host_metrics.host_metric_summary_monthly',
'time_pub': 1740675110.0686553,
'uuid': '9efbb136-2dee-4189-91fd-6edf99c9ce79',
'args': [],
'kwargs': {}}
```
This data is supposed to be JSON-ifable information only, and AWX uses this heavily with a callable queue.
> Fix handling of queues which are callable

- .github/workflows/ci.yml
- Makefile
- dispatcher/control.py
- dispatcher/protocols.py
- mypy.ini
Coming from feedback in https://github.com/ansible/dispatcher/pull/88 and others, this starts to make sense.
I don't think this is a good idea for every library, and it may not be a good idea for all modules within the dispatcher. But the dispatcher is specialized as a code contract for other apps. The `dispatcher/control.py` module is a good example, as it originally came from AWX where we did none of this, but it is externally-facing, and this enables some meaningful progress towards integration in other apps. Speaking more specifically, there is value in the communication that `.control_with_reply` returns a list of dictionaries. This should be elaborated further to clarify that each dictionary in the list is data returned from a dispatcher service, since multiple running dispatcher …
> Start pattern to disallow untyped functions, MyPY updates

- dispatcher/service/next_wakeup_runner.py
Fixes https://github.com/ansible/dispatcherd/issues/114
This appears to come specifically from timeout/delay case, which explains why it didn't obviously break everything else.
> Take a copy of objects before processing

- dispatcher/control.py
- dispatcher/producers/on_start.py
- dispatcher/producers/scheduled.py
- dispatcher/protocols.py
- dispatcher/service/asyncio_tasks.py
- dispatcher/service/blocker.py
- dispatcher/service/control_tasks.py
- dispatcher/service/main.py
- dispatcher/service/next_wakeup_runner.py
- dispatcher/service/pool.py
- dispatcher/service/queuer.py
- dispatcher/utils.py
- tests/integration/test_main.py
- tests/unit/service/producers/test_scheduled_producer.py
- tests/unit/service/test_asyncio_tasks.py
- tests/unit/service/test_pool.py
Fixes https://github.com/ansible/dispatcherd/issues/85
This handles 2 of the classes mentioned there, becoming "processors" which is a new basic type of thing, here.
The 3rd type of the delayer will have its work... well... delayed, because https://github.com/ansible/dispatcherd/pull/108 will be heavily conflicting. That will become both a "processor" and a "next-wakup-runner-thing".
As such, I'm happy with this in terms of the code now. Yes, we could do _better_, and perhaps this was put together a little hastily at first. But this is an improvement and there is an outline of where we're going with it.
There are some performance aspects that could be better, but again, I don't think worse than before. I wanted to address that, but it needs a new class to replace passing around the …
> Split logic for task blocking and queuing into a new module

- dispatcher/service/pool.py
- tests/unit/service/test_worker_liveness.py
Fixes #97
JIRA: [AAP-41124](https://issues.redhat.com/browse/AAP-41124)
Added logic to detect when a worker process has terminated unexpectedly (like from a SIGKILL or crash) without properly notifying the parent process. These workers are now automatically marked with error status, their tasks are counted as canceled, and they're removed from the pool after the standard removal wait period.
This prevents "zombie" workers from cluttering the pool and tasks from appearing to run forever when their worker has died.
**Prerequisites**
* Standard test setup (pytest with dispatcher dependencies)
**Steps to test**
1. Run: `python -m pytest  tests/unit/service/test_worker_liveness.py`
2. Verify all tests pass, showing that dead workers are properly detected, marked, and removed
Rationale behind …
> Detect and clean up unexpectedly terminated worker processes

- Makefile
- README.md
- dispatcher/cli.py
- docker-compose.yml
- docs/config.md
- pyproject.toml
- run_demo.py
- tools/demo/Dockerfile
Fixes https://github.com/ansible/dispatcherd/issues/61
This renames `dispatcher-standalone` to `dispatcherd`, and then adds `dispatcherctl`.
I'm taking advantage of the new entrypoint to remove the 2-terminal-tab instructions from the manual demo. You can just to `docker logs` to see what the server is doing. The `run_demo.py` command doesn't seem to have any problem running against 2 servers as opposed to 1. Everything just happens in duplicate.
> Add a `dispatcherctl` command, rework the demo with it

- dispatcher/brokers/pg_notify.py
When working on https://github.com/ansible/dispatcherd/pull/113 I discovered a strange bug.
When running `./run_demo.py`, sometimes the "aio_tasks" command would incorrectly get the output of the "workers" command, or "running" command. Strange... nothing in the code here seemed could obviously explain that. After all, we are using an ephemeral reply channel with a `uuid4`. How could we get messages from _old_ commands?
There are 2 services running in this case, and that command only listened for 1 reply. So yes, the next reply was still in-flight, but this still doesn't explain things. In the `control.py` module we create a broker using just the reply channel.
The key here is that we _never closed the connection_ and that connection _was still subscribed_ to the channel from the last …
> UNLISTEN when done with session

- dispatcher/brokers/__init__.py
- dispatcher/brokers/pg_notify.py
- dispatcher/control.py
- dispatcher/producers/base.py
- dispatcher/producers/brokered.py
- dispatcher/protocols.py
- dispatcher/service/blocker.py
- dispatcher/service/control_tasks.py
- dispatcher/service/main.py
- dispatcher/service/next_wakeup_runner.py
- dispatcher/service/pool.py
- dispatcher/service/process.py
- dispatcher/service/queuer.py
- mypy.ini
- tests/integration/test_main.py
- tests/unit/service/test_pool.py
- tests/unit/service/test_worker_liveness.py
- tests/unit/test_broker_callbacks.py
- tests/unit/test_connection_saver.py
- tests/unit/test_control_cleanup.py
- tests/unit/test_next_wakeup_runner_errors.py
Fixes https://github.com/ansible/dispatcherd/issues/109
Fixes https://github.com/ansible/dispatcherd/issues/124
Confirmed that the demo still looks good with this change.
This does make structural changes to how control-and-reply works, but I think that is all for the better.
> More type hints & protocols, refactor `control.py` to be broker-based

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/workflows/ci.yml
- README.md
- dispatcherd/__init__.py
- dispatcherd/brokers/pg_notify.py
- dispatcherd/cli.py
- dispatcherd/config.py
- dispatcherd/protocols.py
- dispatcherd/registry.py
- dispatcherd/service/blocker.py
- dispatcherd/service/main.py
- dispatcherd/service/queuer.py
- docs/config.md
- docs/contributing.md
- docs/design_notes.md
- pyproject.toml
- run_demo.py
- tests/unit/test_config.py
Follow up https://github.com/ansible/dispatcherd/pull/134
Rename missing references to `dispatcherd`, mostly docs, logging msgs and links.
> refactor: rename missing refs to dispatcherd

- Makefile
- dispatcher.yml
- dispatcherd/brokers/pg_notify.py
- dispatcherd/brokers/socket.py
- dispatcherd/control.py
- dispatcherd/factories.py
- dispatcherd/producers/brokered.py
- dispatcherd/protocols.py
- dispatcherd/service/main.py
- schema.json
- tests/conftest.py
- tests/integration/brokers/test_socket.py
- tests/integration/test_socket_use.py
This is maybe, perhaps, a solution to https://github.com/ansible/dispatcherd/issues/100 but it is debatable.
However, it was part of the vision of `dispatcherctl` described in https://github.com/ansible/dispatcherd/issues/61
This was more complicated than I expected, but I got it working.
Using the "old" demo with 2 terminal tabs.
```
PYTHONPATH=. dispatcherd
./run_demo.py
```
It now get a bit awkward because you can no longer get a response from multiple servers. But we get to the end of the demo, and it prints everything. In my first pass it broke half-way through because the message was longer than 1024. I think I'm still putting in "reply_to" which the server just ignores.
Protocols need to be updated and basically everything aside from making it run the demo once, which is all it …
> Add Unix socket broker

- dispatcherd/protocols.py
- dispatcherd/service/main.py
- dispatcherd/service/pool.py
- dispatcherd/worker/task.py
- docs/message_formats.md
- tests/data/methods.py
- tests/integration/test_bind.py
- tests/unit/service/test_worker_liveness.py
- tests/unit/worker/test_task_worker.py
Fixes https://github.com/ansible/dispatcherd/issues/71
I just want to demonstrate the gross things so other people don't feel bad doing them, in case someone else goes to pick this up.
From logs running this new test:
```
DEBUG:dispatcher.service.queuer:Dispatching task (uuid=b00b237a-d7bb-4bb0-97e1-98cd0050f1bf) to worker (id=0)
DEBUG:dispatcher.service.pool:Dispatching task (uuid=b00b237a-d7bb-4bb0-97e1-98cd0050f1bf) to worker (id=0)
DEBUG:dispatcher.worker.task:task (uuid=b00b237a-d7bb-4bb0-97e1-98cd0050f1bf) starting tests.data.methods.prints_running_tasks(*[]) on worker 0
{'worker-0': {'task': 'tests.data.methods.prints_running_tasks', 'time_pub': 1741794622.4742262, 'uuid': 'b00b237a-d7bb-4bb0-97e1-98cd0050f1bf', 'args': [], 'kwargs': {}, 'channel': 'test_channel'}} …
```
> Allow running control tasks from worker

- tools/demo/Dockerfile
Dynamic versioning added in https://github.com/ansible/dispatcherd/pull/135 requires git, or else the `pip install` command will error. This adds the git install so that the demo docker-compose can build again.
> Fix demo build by installing git

- dispatcher.yml
- dispatcherd/cli.py
- dispatcherd/factories.py
- dispatcherd/producers/__init__.py
- dispatcherd/producers/base.py
- dispatcherd/producers/brokered.py
- dispatcherd/producers/control.py
- dispatcherd/protocols.py
- dispatcherd/service/control_tasks.py
- dispatcherd/service/main.py
- dispatcherd/service/pool.py
- docs/task_options.md
- schema.json
- tests/conftest.py
- tests/data/methods.py
- tests/integration/test_disruptions.py
- tests/integration/test_main.py
This adds the control commands:
- producers
- run
- status
Only the "producers" actually does much novel, and what it adds isn't much, because we need https://github.com/ansible/dispatcherd/pull/126 to track more meaningful information on the producers.
The "run" command seems silly, but needs https://github.com/ansible/dispatcherd/pull/122, so this _combined with_ that will allow tasks to run control tasks... and one control task can... run other tasks. Put it together, this would allow tasks to run other tasks.
This is extremely demo-able
```
$ dispatcherctl --help
usage: dispatcherctl [-h] [--log-level {DEBUG,INFO,WARNING,ERROR,CRITICAL}] [--config CONFIG] [--task TASK] [--uuid UUID]
[--expected-replies EXPECTED_REPLIES]
{running,cancel,alive,aio_tasks,workers,producers,status}
CLI …
```
> Add more control commands

- dispatcherd/protocols.py
- dispatcherd/service/pool.py
- dispatcherd/service/queuer.py
Fixes https://github.com/ansible/dispatcherd/issues/146
This really just adds "stopping" to what is considered in the now `expected_alive` status list. This may not be obvious. I had to do:
```
>>> a = set(['initialized', 'spawned', 'starting', 'ready', 'stopping', 'exited', 'error', 'retired'])
>>> 
>>> a - set(['retired', 'error', 'exited', 'initialized', 'stopping', 'spawned'])
{'starting', 'ready'}
```
So instead of checking `status not in`, I changed it to just a `status in` check, because there are fewer status items to include, and it becomes more clear.
Also made the `@property` pattern a little more consistent.
> Exclude stopping status from process reaper

- dispatcherd/brokers/socket.py
- dispatcherd/producers/base.py
- dispatcherd/producers/brokered.py
- dispatcherd/protocols.py
- dispatcherd/service/asyncio_tasks.py
- dispatcherd/service/main.py
- dispatcherd/service/next_wakeup_runner.py
- tests/integration/conftest.py
- tests/integration/test_main.py
- tests/integration/test_socket_use.py
I was debugging AWX and had stuff like this:
https://gist.github.com/AlanCoding/36e2256fb74ecc6556d6f5f384bd4974
```
Task-215555:
done: false
stack: "Stack for <Task pending name='Task-215555' coro=<Event.wait() running\
\ at /usr/lib64/python3.11/asyncio/locks.py:213> wait_for=<Future pending\
\ cb=[Task.task_wakeup()]> cb=[_wait.<locals>._on_completion() at /usr/lib64/python3.11/asyncio/tasks.py:519]>\
\ (most recent call last):\n  File \"/usr/lib64/python3.11/asyncio/locks.py\"\
, line 213, in wait\n    await fut\n"
```
This made me very nervous. Does this list contain _too_ many tasks? Did a task go rogue and fail to get cleaned up? If that happened, how could I know?!
It seems the only option is to identify the purpose of all tasks, and identify them with a name that hints at this …
> Add names to all asyncio tasks

- .github/workflows/ci.yml
- README.md
- dispatcher.yml
- dispatcherd/factories.py
- dispatcherd/protocols.py
- dispatcherd/service/main.py
- dispatcherd/service/metrics.py
- pyproject.toml
- schema.json
- tests/integration/test_metrics_use.py
Replaces https://github.com/ansible/dispatcherd/pull/116
This takes a pivot from what I initially suggested, which was to have AWX start the thread.
That was a terrible idea, because nobody anywhere should be starting any threads here. Our hangup was that the library `prometheus-client` didn't obviously implement an asyncio version of their server. Oh, but they did! It just needs an intermediary of uvicorn.
After learning about how we can use this full-asyncio solution, I'm very comfortable with implementing the entire thing natively in dispatcherd. This PR is intended to offer the meat of the integration work for that - putting the metrics kwargs into the dispatcherd config system, adding that tasks to our tasks.
By default this will not be enabled, which is what you get if you don't …
> Add a metrics server that can be optionally enabled

- dispatcherd/protocols.py
- dispatcherd/service/blocker.py
- dispatcherd/service/control_tasks.py
- dispatcherd/service/delayer.py
- dispatcherd/service/main.py
- dispatcherd/service/next_wakeup_runner.py
- dispatcherd/service/pool.py
This stitches together 2 other refactors I already landed:
- Introduce the generic notion of a task "processor" which can "consume" a task at various points with some implementation differences based on the order in the call stack.
- The delayer runs early, and has the special ability of running an asyncio task. End result of tasks it consumes is a callback that passes it to the next stage of processing.
- The blocker avoids running 2 tasks of the same method and call args based on specified `on_duplicate` behavior. End result of consumed tasks is a queue that is consumed in `drain_queue`, or discarded
- The queuer has access to pool workers, and it places or consumes a task based on current capacity in the pool End result of consumed tasks is, again, a queue consumed by `drain_queue`. …
> Split task-delayer into new module, it is now a task "processor"

- dispatcherd/config.py
- dispatcherd/factories.py
- dispatcherd/producers/brokered.py
- dispatcherd/producers/control.py
- dispatcherd/producers/on_start.py
- dispatcherd/producers/scheduled.py
- dispatcherd/protocols.py
- dispatcherd/service/asyncio_tasks.py
- dispatcherd/service/blocker.py
- dispatcherd/service/delayer.py
- dispatcherd/service/main.py
- dispatcherd/service/next_wakeup_runner.py
- dispatcherd/service/pool.py
- dispatcherd/service/process.py
- dispatcherd/worker/task.py
- tests/integration/test_disruptions.py
- tests/integration/test_main.py
- tests/unit/service/producers/test_scheduled_producer.py
- tests/unit/service/test_blocker.py
- tests/unit/service/test_next_wakeup_runner.py
- tests/unit/service/test_pool.py
- tests/unit/service/test_worker_liveness.py
- tests/unit/test_next_wakeup_runner_errors.py
Fixes https://github.com/ansible/dispatcherd/issues/140
The code might not always look cleaner as a result of this change, but more importantly, the internal state of the program is simplified. There are no longer multiple `shutting_down` flags. There's just 1 event, and anything can either check it or wait for it. Those other flags were subservient to this event (which already existed anyway). The ownership of that `exit_event` is changed from `DispatcherMain` to "anyone can pull the fire alarm".
> Use a shared set of asyncio objects for code flow control

- .github/workflows/ci.yml
- Makefile
- dispatcherd/factories.py
- dispatcherd/protocols.py
- dispatcherd/service/pool.py
- dispatcherd/service/process.py
- dispatcherd/testing/__init__.py
- dispatcherd/testing/asyncio.py
- dispatcherd/testing/subprocess.py
- pyproject.toml
- schema.json
- tests/conftest.py
- tests/integration/test_control_tasks.py
- tests/integration/test_main.py
- tests/integration/test_metrics_use.py
- tests/integration/test_socket_use.py
- tests/unit/service/test_pool.py
Fixes https://github.com/ansible/dispatcherd/issues/9
Fixes https://github.com/ansible/dispatcherd/issues/127
I described in more recent issues - the intent would be to ultimately replace all the existing async tests.
This has a nasty warning:
```
/home/alancoding/venvs/awx/lib64/python3.12/site-packages/psycopg/_connection_base.py:146: ResourceWarning: connection <psycopg.Connection [IDLE] (host=localhost port=55777 user=dispatch database=dispatch_db) at 0x7efbef973710> was deleted while still open. Please use 'with' or '.close()' to close the connection
```
I expect that will be resolved with connection closing @art-tapin did in https://github.com/ansible/dispatcherd/pull/121. Maybe.
Right now this test is slow, but the idea is that we'll start to reuse the fixture between tests and …
> Start running synchronous tests, separate from asyncio tests

- .github/workflows/ci.yml
- requirements_dev.txt
Ensure httpx is a dev dependency and make requirements_dev as single source of truth for dependencies.
> chore: ensure httpx as dev dependency

- dispatcherd/config.py
- dispatcherd/service/pool.py
- schema.json
- tests/unit/service/test_pool.py
- tests/unit/test_config.py
In the most of the cases we want to set the max number of workers equal to the cpu cores available. This can be set by default by the system if the configuration does not provide a value, allowing a more concise configuration. 
It also removes the default at the instantiation level, unaligned with previous existing default value in the class.
> feat: set max_workers by default based on cpu count

- dispatcherd/processors/queuer.py
Since I've been going through AWX logs a lot, I have been looking at a lot of log messages related to queuing tasks. But ordinarily, this is a non-story. If we have a very very high queue count, then it could be important.
So this approach uses a gradually increasing log level as queue pressure increases. I mainly just tested with the demo.
```
DEBUG:dispatcherd.service.pool:Dispatching task (uuid=internal-2039) to worker (id=6)
DEBUG:root:Queueing task (uuid=internal-2040), due to lack of capacity, queued_ct=0
INFO:root:Queueing task (uuid=internal-2041), due to lack of capacity, queued_ct=1
WARNING:root:Queueing task (uuid=internal-2042), due to lack of capacity, queued_ct=2
```
> Make queuing message a lower log level
